language: python
python:
  - 2.7
  
os: linux

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install numpy scipy pytest numba dill sh
  - conda install -c theochem horton
  - pip install python-coveralls pytest-cov
  - pip install --upgrade python-coveralls 
  
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then pytest -vv data/testfiles/test_*.py --cov;
    else pytest -vv data/testfiles/test_*.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

notifications:
  email: false
